name: Python Test Automation

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        cd demos
        pip install -r requirements.txt

    - name: Run Pytest with Allure
      run: |
        cd demos
        pytest --alluredir=allure-results --cov=src --cov-report=xml || echo "pytest_failed=true" >> $GITHUB_ENV

    # ✅ Install Allure CLI
    - name: Install Allure
      run: |
        sudo apt-get update
        sudo apt-get install -y default-jre
        wget https://github.com/allure-framework/allure2/releases/download/2.27.0/allure-2.27.0.tgz
        tar -zxvf allure-2.27.0.tgz
        sudo mv allure-2.27.0 /opt/allure
        sudo ln -s /opt/allure/bin/allure /usr/bin/allure

    # Download the previous reports for the trend
    - name: Download previous report
      uses: actions/checkout@v4
      with:
        ref: gh-pages
        path: gh-pages

    #Copy history and save the history
    - name: Copy Allure History
      run: |
        mkdir -p demos/allure-results/history
        cp -r gh-pages/history/* demos/allure-results/history || true

    # ✅ Generate HTML report
    - name: Generate Allure Report
      if: always()
      run: |
        cd demos
        allure generate allure-results -o allure-report --clean

    - name: Upload coverage to Codecov
      if: always()
      uses: codecov/codecov-action@v4
      with:
        files: demos/covergae.xml

    # ✅ Deploy to GitHub Pages
    - name: Deploy to GitHub Pages
      if: always()
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: demos/allure-report
        keep_files: true

    - name: Fail pipeline if tests failed
      if: env.pytest_failed == 'true'
      run: exit 1